# Generated by Django 5.2.7 on 2025-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('related_roles', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
