# Generated by Django 5.2.7 on 2025-10-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internhub', '0002_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link_to_application',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
