# Generated by Django 5.2.7 on 2025-10-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internhub', '0003_job_link_to_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link_to_application',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
