# Generated by Django 5.2.7 on 2025-10-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internhub', '0004_alter_job_link_to_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Received'), ('rejected', 'Rejected'), ('saved', 'Saved / Draft'), ('ghosted', 'Ghosted/ Ignored'), ('assessment', 'Assessment Required')], default='applied', max_length=20),
        ),
    ]
